spring:
  batch:
    initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/RegistraireJava
    username: postgres
    password: postgres
    initialization-mode: always
    initialize: true
